# Generated by Django 2.0.5 on 2018-08-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_auto_20180811_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heroinfo',
            old_name='hcontext',
            new_name='hcontent',
        ),
    ]
